### ISSUE TITLE
link_to doesn't redirect to page

### ISSUE THREAD

**Issue by ioanacrant** [xuyuwei/resumebox#2]
In home.html.erb line23
Including the class: "scrollto" makes the link broken even though hovering over it gives the right link

**Comment by ioanacrant** [comment]
Signup works, About doesn't

**Comment by youwayx** [comment]
ok i have no idea what you mean by 'scrollto'

edit: nvm i deleted it

**Comment by youwayx** [comment]
fixed signup path link
