### ISSUE TITLE
Upload resume button isn't formatting

### ISSUE THREAD

**Issue by ioanacrant** [xuyuwei/resumebox#3]
"upload resume" in views/users/show.html.erb is showing up on screen weirdly after adding link

**Comment by youwayx** [comment]
fixed this i think

**Comment by ioanacrant** [comment]
Nope 
![image](https://cloud.githubusercontent.com/assets/8014346/6590233/aba0ad0c-c783-11e4-9275-ba73bed01c7a.png)
